Create Database Healthcare;
Use Healthcare;
Select * from Healthcare;

-- 1. Retrieve the names of all patients in the database
Select Name from Healthcare;

-- 2. List the unique medical conditions present in the dataset
select distinct Medical_Condition from Healthcare;

-- 3. Find the total number of doctors in the healthcare system
select count(distinct(Doctor)) from Healthcare;


-- 4. Retrieve the details of all female patients
select * from Healthcare where Gender = 'Female';

-- 5. What is the average age of patients in the database
select avg(Age) from Healthcare;

-- 6. Identify the patients who have more than one medical condition
SELECT Name, count(Medical_Condition) from Healthcare 
group by Name having count(Medical_Condition) > 1;


-- 7. List the names of all doctors
select Doctor from healthcare;


-- 8.Identify the most common medical condition among patients
select Medical_Condition, count(*) as Medical_Condition_Count
from Healthcare
group by Medical_Condition
having COUNT(*) = (select max(Medical_Condition_Count)
    from (select count(*) as Medical_Condition_Count
        from Healthcare
        group by Medical_Condition) as Subquery);


-- 9.Find the patients who are older than 60 years and have diabetes.
select Name, Age, Medical_Condition from Healthcare where Age > 60 and Medical_Condition = 'Diabetes';



-- 10.Calculate the total revenue generated by the healthcare system.
select sum(Billing_Amount) as Total_Revenue_Generated from Healthcare ;


-- 11.Find the doctor with the oldest patient.
select Doctor, Age from Healthcare where Age = (select max(Age) from Healthcare);



-- 12.Calculate the average duration of medical visits.
select avg(Duration) from Healthcare;



-- 13.Give the names of patients whose name starts with A.
select Name from Healthcare where Name like 'A%';


-- 14.How many male and female patients are there in dataset.
select Gender, count(Gender) from Healthcare group by Gender;


-- 15.how many patients are normal.
select Test_Results, count(Test_Results) from Healthcare where Test_Results = 'Normal' group by Test_Results;


-- 16.how many patients are abnormal or Inconclusive.
select Test_Results, count(Test_Results) from Healthcare where Test_Results in ('Inconclusive','Abnormal') group by Test_Results;


-- 17.how many patients of blood group AB+ are there of age above 52.
select Blood_Type, count(Age) from Healthcare where Blood_Type = 'AB+' and Age >= 52;


-- 18. how many patients have paid the bill above 24890.
select count(Billing_Amount) from Healthcare where Billing_Amount > 24890;


-- 19. what are the names of patients having Asthma.
select Name, Medical_Condition from Healthcare where Medical_Condition = 'Asthma'; 


-- 20. how many patients have cancer.
select Medical_Condition, count(Medical_Condition) from Healthcare where Medical_Condition = 'Cancer';


-- 21. what are the names and blood groups of patients admitted to room no. 292.
select Name,Blood_Type,Room_Number from Healthcare where Room_Number = 292;

-- 22. how many males have Arthritis.
select Gender,Medical_Condition,count(Medical_Condition) from Healthcare 
where Gender = 'Male' and 
Medical_Condition = 'Arthritis'
group by Gender and Medical_Condition;


-- 23. How many patients were admitted to Harris and Sons hospital.
select Hospital, count(Hospital) from Healthcare where Hospital = 'Harris and Sons';


-- 24. what are the names of patients whose Insurance Provider are Cigna.
select Name,Insurance_Provider from Healthcare where Insurance_Provider = 'Cigna';

-- 25. Name the Medical Condition having patients whose ages is greater than average age
select Medical_Condition, count(Age) from Healthcare where Age> (select avg(Age) from Healthcare) group by Medical_Condition; 
 